### ISSUE TITLE
MPI plane depth values vary across scenes

### ISSUE THREAD

**Issue by zzyunzhi** [ken2576/deep-3dmask#2]
Hi, 

Thank you for the great work! You used depth bounds obtained from COLMAP to determine the near and far depth values for MPI planes (code [here](https://github.com/ken2576/deep-3dmask/blob/6a3307df93ea383dee9e63888acfc44416c1c085/train_mask/datasets/mvcam.py#L206)), which will vary for each scene. 

Could you explain a bit more why it's implemented this way? If I'm understanding correctly, the mask network is agnostic of the near and far value, and thus might be confused if the MPI planes do not correspond to fixed depth values?

**Comment by adahbingee** [comment]
As as per my understanding,
The original 2018 MPI uses fixed uniform distribution planes across the scene volume which is not best for such scene complex foreground and simple background.
Then 2019 LLFF uses miltiple-MPI for better performance.
The recent research use dynamic placed plane according to COLMAP 3D feature point statistics(place more planes at dense distance).

**Comment by ken2576** [comment]
Yes, just like what @adahbingee said, ideally the near/far plane should be dynamically placed for maximal coverage.
For example, let's assume we fix the near/far plane values to be 1~100 meters.
Then, if we are given a scene with depths ranging from 1 to 3 meters, we will waste some depth samplings on the planes that are beyond 3m.
This would cause the scene to have depth discretization artifacts similar to the ones shown in Fig. 1. in Srinivasan et al. CVPR 2019 ([https://arxiv.org/pdf/1905.00413.pdf](https://arxiv.org/pdf/1905.00413.pdf)), because there are not enough samples in the correct depth range.
As a result, it is always better to dynamically assign the depth ranges such that it can enclose the scene.
You can refer to [this line](https://github.com/Fyusion/LLFF/blob/c6e27b1ee59cb18f054ccb0f87a90214dbe70482/llff/poses/pose_utils.py#L82) in LLFF. They used COLMAP feature points to determine the approximated scene depths.

Additional note: this technical nuance is also important for newer methods like [NeRF](https://github.com/bmild/nerf) as NeRF and MPI both share the same idea of volumetric rendering.

**Comment by zzyunzhi** [comment]
1. For this work as well as LLFF, the MPI network uses binocular inputs and therefore is expected to output the absolute depth values. I understand that having dynamically adapted depth range will reduce the discretization artifacts, but do you expect the MPI model to generalize well if the model is not aware of the new near and far depth values during test time? With the dynamic and therefore unknown near and far depth values, the MPI model won't be able to associate the depth plane with absolute depth values anymore? 
2.  In Tucker 2020 (https://single-view-mpi.github.io/single_view_mpi.pdf), since they use monocular MPI, the depth prediction is scale invariant. They used sparse point cloud from COLMAP to determine depth scale (Section 3.2 equation (2)), do you think that will have similar effect as dynamically deciding the depth range of MPI planes? If the sparse point cloud data is available, I can imagine computing the depth scale as done in Tucker 2020 and using that to decide the depth plane values, which will be potentially more robust to point cloud outliers.

**Comment by ken2576** [comment]
Sorry for the late reply.
1. The network does not take the depth values as input. Instead, it takes the plane sweep volume. Essentially, it is looking at the PSVs and checking if they converge. If they do, then the network would place objects on that plane. As such, the MPI model does not explicitly know the absolute depth values.
2. You can directly use the point cloud data to compute the depth bounds for multi-view cases. I think why they computed that is because they want to have the depth regularized to generate accurate depth maps. That is not what we are doing here. Our focus is to maximize the coverage of the planes and setting the bound with sparse point cloud should be sufficient. (Note that LLFF is taking the nearest 0.1 and the 99.9th percentile so it can reject some outliers.)

**Comment by zzyunzhi** [comment]
Thanks! That answers my questions. Closing the issue now.
